Homework #1. Task #3. Филимонов Игорь
IgorFilimonov/spbu_2020_kotlin_homeworks pull request #5
Opened 2021-03-18 17:24 UTC by IgorFilimonov

2021-03-18 21:51 UTC, nbirillo requested changes

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +class AddToBeginning(private val value: Int?, private val storage: PerformedCommandStorage) : Action {
А зачем ты вообще даешь возможность добавлять null? если ты в init это хэндлишь? сделай, чтобы просто числа были, без null

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +        storage.numbers.add(0, value!!.toInt())
ну и собственно тогда !! использовать не надо будет (но его в целом использовать плохо)

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +class AddToEnd(private val value: Int?, private val storage: PerformedCommandStorage) : Action {
Тот же комментарий про value

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +        storage.numbers.add(value!!.toInt())
Тот же комментарий про !!

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +private fun move(startIndex: Int, endIndex: Int, storage: PerformedCommandStorage) {
Сделай более общую функцию, например которая принимает список, а не сторадж. Зачем сторадж то туда сюда гонять?

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +    private var endIndex: Int? = null
Тот же комментарий - зачем null?

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +    private lateinit var storage: PerformedCommandStorage
Почему она lateinit? почему не в конструкторе?

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +        }
Уто уберется, когда уберешь null

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +        move(startIndex!!.toInt(), endIndex!!.toInt(), storage)
!! тоже не будет

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/actions.kt
> +        move(endIndex!!.toInt(), startIndex!!.toInt(), storage)
!! тоже не будет

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +const val COMMAND_TYPE5 = 5
Ну назови их осмысленно как-то что ли

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +            val value = readLine()?.toIntOrNull()
Код повторяется, можно вынести в функцию. При этом для COMMAND_TYPE3 тоже можно будет ее вызвать, только два раза

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +        else -> {}
А это странно выглядит. Может ошибку кидать? (можно тогда объединить с null)

2021-03-18 21:51 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +fun main() {
![image](https://user-images.githubusercontent.com/8993915/111702380-3a7c0e00-884d-11eb-8216-8775917723b3.png)

2021-03-24 17:43 UTC, elena-lyulina requested changes

2021-03-24 17:43 UTC, elena-lyulina commented on src/main/kotlin/homework1/actions.kt
> +}
эта функция является частью реализации Move, давай она будет внутри класса

2021-03-24 17:43 UTC, elena-lyulina commented on src/main/kotlin/homework1/task3.kt
> +const val PRINT_NUMBERS = 5
давай это сделаем enum? тогда по ним можно будет итерироваться, можно будет удобнее работать с when и тд

2021-03-24 17:43 UTC, elena-lyulina commented on src/main/kotlin/homework1/actions.kt
> +        moveNumbers(from, to, storage.numbers)
тут теперь наоборот надо с to на from менять)

2021-03-25 09:35 UTC, IgorFilimonov commented on src/main/kotlin/homework1/task3.kt
> +const val PRINT_NUMBERS = 5
В последнем коммите я сделал enum, но как теперь избежать magic number?

2021-03-25 10:27 UTC, elena-lyulina commented on src/main/kotlin/homework1/task3.kt
> +const val PRINT_NUMBERS = 5
первый из вариантов (более хороший) -- использовать [ordinal](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-enum/ordinal.html) вместо value, который примерно то же самое означает
второй из вариантов -- понять, что в данном случае detekt не совсем прав и мы используем числа 1-5 для тестирования, поэтому можем добавить аннотацию @Suppress("MagicNumber") перед enum

2021-03-25 14:09 UTC, elena-lyulina approved these changes
Класс, спасибо

2021-03-25 14:09 UTC, merged